version: "3"

services:
  server-manager:
    image: seejy/assetto-server-manager:latest
    container_name: ac
    ports:
    # the port that the assetto server runs on (may vary depending on your configuration inside server manager)
    - "9600:9600"
    - "9600:9600/udp"
    # the port that the assetto server HTTP API runs on.
    - "8081:8081"
    # you may also wish to bind your configured UDP plugin ports here. 
    - "8082:8082" # Content Manager Wrapper port (enables downloading missing content from Content Manager)
    expose:
      - "8772"
    environment:
      - "VIRTUAL_HOST=ac.zairecloud.pt"
      - "VIRTUAL_PORT=8772"
      - "LETSENCRYPT_HOST=ac.zairecloud.pt"
    volumes: 
    # volume mount the entire server install so that 
    # content etc persists across restarts
    - ./server-manager:/home/assetto/server-manager
    - ./server-manager/assetto:/home/assetto/server-manager/assetto
    restart: unless-stopped
    networks:
      - nginx-proxy_network

networks:
  nginx-proxy_network:
    external: true